### ISSUE TITLE
Support for User (local) Timezone

### ISSUE THREAD

**Issue by saschawagner** [mailru/jira-plugins-mailrucal#19]
Calendar is displaying tickets based on server time. 
Jira user in different timezones may see the ticket dates in their local time. 
It would be nice to either select a timezone or get this value from  the Jira user value.

**Comment by mashintsev** [comment]
Hi.
Which plugin version do you use? In latest version all date-time fields use use time zone from user profile settings.

**Comment by saschawagner** [comment]
Jira v6.3.14
2.1.3

**Comment by mashintsev** [comment]
Upgrade to the latest version. https://marketplace.atlassian.com/manage/plugins/ru.mail.jira.plugins.mailrucal/versions

**Comment by saschawagner** [comment]
Cool. Thank you. Haven't seen this in the release note.

**Comment by mashintsev** [comment]
We fixed this in 2.1.10 - "Bugfix for French locale. Bugfix event date timezone" https://marketplace.atlassian.com/plugins/ru.mail.jira.plugins.mailrucal/versions#b370

**Comment by saschawagner** [comment]
Oh I see. I am sorry.

**Comment by saschawagner** [comment]
Thank you.

**Comment by saschawagner** [comment]
Upgrading fixed it. 

BTW we accidentally  upgraded to 2.2  which cause calendar not working . Ending into an undefined error. However uninstall and installing the correct plugin fixed it.  Also all existing calendars are still available after reinstalling.

**Comment by chadcw** [comment]
Can you confirm this is still in 2.1.12?  I recently installed the plugin, for Jira 6.4.12 Version:
2.1.12 via Marketplace and via link in the comments and it is still showing dueDate as Server time not user profile timezone.  I couldn't find anything in the logs to suggest errors so not sure what to try next. Any suggestions?

**Comment by andreymolchanov** [comment]
chadcw, is the problem still actual? Please use the latest version available, it should help.
